import turtle
#trying new modifications
rithin = turtle.Turtle()
rithin.shape("turtle")
rithin.color("black","red")
rithin.speed(3)
turtle.Screen().bgcolor("red")
rithin.left(45)
rithin.pensize(3)
rithin.pendown()
rithin.circle(100,360,4)
rithin.right(45)
rithin.penup()
rithin.goto(-100,75)
rithin.write("Happy Birthday!!!")
turtle.Screen().exitonclick()