import turtle
rithin = turtle.Turtle()
rithin.color("green")
rithin.shape("turtle")
rithin.begin_fill()
rithin.forward(200)
rithin.right(90)
rithin.forward(200)
rithin.right(90)
rithin.forward(200)
rithin.right(90)
rithin.forward(200)
rithin.end_fill()
rithin.color("red")
rithin.begin_fill()
rithin.right(45)
rithin.forward(140)
rithin.right(90)
rithin.forward(140)
rithin.end_fill()
rithin.left(45)
rithin.left(90)
rithin.forward(100)
rithin.left(90)
rithin.forward(30)
rithin.left(90)
rithin.forward(70)
turtle.Screen().exitonclick()

