import turtle
#user_input = "brave"
#user_input = "smart"
#user_input = "dark arts"
user_input = "humble"
rithin = turtle.Turtle()
turtle.screensize(500,1200)
rithin.shape("turtle")
rithin.pensize(3)
def Gryffindor():
    rithin.color("grey")
    rithin.forward(50)
    rithin.left(90)
    rithin.forward(100)
    rithin.penup()
    rithin.goto(0,0)
    rithin.pendown()
    rithin.forward(100)
    rithin.left(90)
    rithin.forward(50)
    rithin.penup()
    rithin.goto(50,100)
    rithin.pendown()
    rithin.right(180)
    rithin.forward(50)
    rithin.left(90)
    rithin.forward(50)
    rithin.penup()
    rithin.goto(-50,100)
    rithin.pendown()
    rithin.forward(50)
    rithin.right(90)
    rithin.forward(50)
    rithin.left(90)
    rithin.forward(200)
    rithin.right(45)
    rithin.forward(50)
    rithin.right(90)
    rithin.forward(50)
    rithin.right(45)
    rithin.forward(200)
    rithin.left(90)
    rithin.forward(25)
def Ravenclaw():
    rithin.color("yellow")
    rithin.forward(200)
    rithin.left(90)
    rithin.forward(50)
    rithin.left(45)
    rithin.forward(50)
    rithin.dot(10)
    rithin.left(90)
    rithin.forward(50)
    rithin.right(90)
    rithin.forward(50)
    rithin.dot(10)
    rithin.left(90)
    rithin.forward(50)
    rithin.right(90)
    rithin.forward(50)
    rithin.dot(10)
    rithin.left(90)
    rithin.forward(50)
    rithin.left(45)
    rithin.forward(50)
    rithin.left(90)
def Slytherine():
    rithin.shape("classic")
    rithin.shapesize(2)
    rithin.color("green")
    rithin.circle(50,180)
    rithin.penup()
    rithin.goto(0,200)
    rithin.pendown()
    rithin.circle(50,180)
    rithin.penup()
    rithin.goto(0, 200)
    rithin.pendown()
    rithin.circle(50, 180)
    rithin.penup()
    rithin.goto(0,0)
    rithin.pendown()
    rithin.left(45)
    rithin.forward(10)
    rithin.left(90)
    rithin.forward(10)
    rithin.begin_fill()
    rithin.circle(70, 180)
    rithin.penup()
    rithin.goto(110,225)
    rithin.left(45)
    rithin.pendown()
    rithin.circle(75,180)
    rithin.penup()
    rithin.goto(110,225)
    rithin.pendown()
    rithin.circle(40,180)
    rithin.right(20)
    rithin.forward(100)
    rithin.left(45)
    rithin.forward(50)
    rithin.left(45)
    rithin.left(88)
    rithin.forward(50)
    rithin.penup()
    rithin.left(100)
    rithin.forward(25)
    rithin.pendown()
    rithin.dot(15,"red")
def Hufflepuff():
    rithin.shape("turtle")
    rithin.color("yellow")
    rithin.pensize(3)
    rithin.right(90)
    rithin.forward(200)
    rithin.left(90)
    rithin.forward(200)
    rithin.left(90)
    rithin.forward(200)
    rithin.penup()
    rithin.goto(100,-200)
    rithin.pendown()
    rithin.right(180)
    rithin.forward(200)
    rithin.right(90)
    rithin.forward(50)
    rithin.left(90)
    rithin.forward(50)
    rithin.right(90)
    rithin.forward(50)
    rithin.left(90)
    rithin.forward(50)
    rithin.left(90)
    rithin.forward(200)
    rithin.left(90)
    rithin.forward(50)
    rithin.left(90)
    rithin.forward(50)
    rithin.right(90)
    rithin.forward(50)
    rithin.left(90)
    rithin.forward(50)
    rithin.penup()
    rithin.goto(0,0)
    rithin.left(90)
    rithin.forward(25)
    rithin.right(90)
    rithin.pendown()
    rithin.circle(75,180)
    rithin.penup()
    rithin.goto(0,0)
    rithin.forward(200)
    rithin.right(90)
    rithin.forward(175)
    rithin.left(90)
    rithin.pendown()
    rithin.circle(75,180)
if user_input == "brave" :
    Gryffindor()
elif user_input == "smart" :
    Ravenclaw()
elif user_input == "dark arts" :
    Slytherine()
else :
    Hufflepuff()
turtle.Screen().exitonclick()


