string_example = "This is a string"
length = len(string_example)
print("This is length function(shows the length of a string)", length)
split = string_example.split("s")
print("This is split function : ", split)
find = string_example.find("s")
print("This is find function(it tells the placement of  a letter) = ", find)
join = "s".join(split)
print("This is join function : ", join)
splitlines = string_example.splitlines()
print("This is splitlines function : ", splitlines)
strip = string_example.strip("This")
print("This is strip function (removes a word): ", strip)
upper = string_example.upper()
print("This is upper function (uppercase): ", upper)
lower = string_example.lower()
print("This is lower function (lowercase): ", lower)
title = string_example.title()
print("This is title function (titlecase): ", title)
replace = string_example.replace(" ", "_")
print("This is replace function (replace spaces into underscore): ", replace)
count = string_example.count("s")
print("This is the count function(counts the number of times of s) : ", count)
is_digit = string_example.isdigit()
print("This is the is_digit(tells if a string is a digit or not) function: ", is_digit)
is_alpha = string_example.isalpha()
print("This is the is_alpha(tells if a string is made of alphabets or not) function: ", is_alpha)


